// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// This file contains the tokens for attributes stored in flash


// Identifier tags for tokens
#define CREATOR_VIRTUAL_DIP_SWITCH     0x5648


// Types for the tokens
#ifdef DEFINETYPES
#endif // DEFINETYPES


// Actual token definitions
#ifdef DEFINETOKENS
 DEFINE_BASIC_TOKEN(VIRTUAL_DIP_SWITCH, int8u, 0xFF)
#endif // DEFINETOKENS


// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint) do {\
} while(FALSE)


// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER do {\
} while(FALSE)


